name: fast_jetclass

channels:
  - conda-forge
  - defaults

dependencies:
  - python=3.10
  - pyyaml=6.*
  - numpy=1.23.*
  - python-wget=3.2
  - scikit-learn=1.6.*
  - matplotlib=3.10.*
  - scikit-learn
  - matplotlib
  - tqdm
  - uproot
  - awkward          # <— add this
  - vector   
  - pyarrow
  - xrootd
  - pandas
  - ipdb
  - pip

  - pip:
    - tensorflow[and-cuda]==2.14
    - tensorflow-model-optimization==0.8.0
    - qkeras==0.9
