---
outdir: 'SC8_onefile_synth'
data_hyperparams:

  root: "/work/aserinke/l1-jet-id/data/test"

  nconst: 8

  kfolds: 2

  datasets:
    all:
      - "root://eosuser.cern.ch//eos/cms/store/group/dpg_trigger/comm_trigger/L1Trigger/lroberts/sc8_with_classes.root"

  test_size: 0.20
  random_state: 42

model_type: "sinvariant"
model_hyperparams:
  phi_layers: [52, 20, 4]
  rho_layers: [36, 4, 4]
  activ: "tanh"
  aggreg: "max"
  output_dim: 1
  nbits: 8

compilation_hyperparams:
  optimizer: "adam"
  optimizer_hps:
    learning_rate: 0.001
    jit_compile: false
  optimizer_callbacks:
    early_stopping:
      monitor: "val_accuracy"
      patience: 20
    lr_decay:
      monitor: "val_accuracy"
      factor: 0.8
      patience: 10
      min_lr: 0.0001

  loss: "binary_crossentropy"
  metrics: ["accuracy"]
  early_stopping: 20

training_hyperparams:
  batch_size: 2048
  epochs: 1000
  shuffle: True
  verbose: 2
