---
outdir: 'SC8_synth'
data_hyperparams:

  root: "/work/aserinke/l1-jet-id/data/test"

  nconst: 8

  kfolds: 2

  datasets:
    bkg:
      - "root://eosuser.cern.ch//eos/cms/store/group/dpg_trigger/comm_trigger/L1Trigger/lroberts/jetTaggingInputs/SingleNeutrino_PU200_1746011721/data/singneut.root"
    sig:
      - "root://eosuser.cern.ch//eos/cms/store/group/dpg_trigger/comm_trigger/L1Trigger/lroberts/jetTaggingInputs/lightHbb_M20to80_Pt50to200_1745321368/data/lightH.root"

  test_size: 0.2
  random_state: 42

model_type: "sinvariant"
model_hyperparams:
  phi_layers: [64]
  rho_layers: [32, 4]
  activ: "relu"
  aggreg: "mean"
  output_dim: 2
  nbits: 8

compilation_hyperparams:
  optimizer: "adam"
  optimizer_hps:
    learning_rate: 0.0029
    jit_compile: false
  optimizer_callbacks:
    early_stopping:
      monitor: "val_accuracy"
      patience: 20
    lr_decay:
      monitor: "val_accuracy"
      factor: 0.8
      patience: 10
      min_lr: 0.0001

  loss: "softmax_with_crossentropy"
  metrics: ["accuracy"]
  early_stopping: 20

training_hyperparams:
  batch_size: 128
  epochs: 1000
  shuffle: True
  verbose: 2
