#!/usr/bin/env python

# Run the testing of the interaction network.
import argparse
import yaml
import os

from fast_jetclass.deepsets.synthesize import main


parser = argparse.ArgumentParser(formatter_class=argparse.ArgumentDefaultsHelpFormatter)
parser.add_argument("--config_file", type=str, help="HLS4ML synthesis config.")
parser.add_argument("--model_dir", type=str, help="Directory with model to synth.")
parser.add_argument('--diagnose', action=argparse.BooleanOptionalAction)
parser.add_argument("--gpu", type=str, default="0")
parser.add_argument("--seed", type=int, default=123, help="Seed for shuffling const.")
parser.add_argument("--sample", type=int, default=0, help="Index of the validation sample to trace (default: 0)")
args = parser.parse_args()

os.environ["CUDA_VISIBLE_DEVICES"] = args.gpu

with open(args.config_file, "r") as stream:
    synthesis_config = yaml.load(stream, Loader=yaml.Loader)

main(args, synthesis_config)
